{{- if .Values.wildcard.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      sprouter.geeko.me/enabled: "true"
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - *.{{ .Values.wildcard.domain }}
    - {{ .Values.wildcard.domain }}
{{- end }}