{{- if .Values.wildcard-certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      sprouter.geeko.me/enabled: "true"
  secretName: wildcard-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    {{ .Values.wildcard-certificate.domains | toYaml | indent 4 }}
{{- end }}